### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by bbbbbw** [dd-center/DD_real_time_radar_frontend#4]
首先恭喜诸位同传和技术man！同为一名程序员，深知建站不易。不过还是想提几个（也许大佬们已经注意到或者已经着手修改的）微小的建议。

0. 移动端适配欠佳，希望能在以后更新中改进吧
1. 首页一次性刷出近400条数据略显臃肿，是否可以考虑分页？
2. 个人页面，同传弹幕统计中的1970年1月……虽然可以理解但是修改起来应该也不难

最后谨作为一个D…AN推献上我的祝福

**Comment by pren1** [comment]
多谢你的建议！

> 首先恭喜诸位同传和技术man！同为一名程序员，深知建站不易。不过还是想提几个（也许大佬们已经注意到或者已经着手修改的）微小的建议。
>
> 1. 移动端适配欠佳，希望能在以后更新中改进吧

在做了，前端man估计这周应该可以完成

> 2. 首页一次性刷出近400条数据略显臃肿，是否可以考虑分页？

我之后会和其他人进行讨论，谢谢建议～

> 3. 个人页面，同传弹幕统计中的1970年1月……虽然可以理解但是修改起来应该也不难
> 

预计在将来会解决（摸

> 最后谨作为一个D…AN推献上我的祝福

草wwwwwww
