### ISSUE TITLE
"魔宵Sakyu_Official"已更名为“夏诺雅_shanoa”

### ISSUE THREAD

**Issue by Tiandians** [dd-center/DD_real_time_radar_frontend#9]
如题：

直播间`1321846`在`huolonglive`网页中仍显示为`魔宵Sakyu_Official`，应更名为`夏诺雅_shanoa`

建议更改后端数据获取方式，直播间所有者名称时常更新

**Comment by pren1** [comment]
感谢建议，但是b站对爬虫有限制，导致更新起来相当麻烦。。最近应该会解决

**Comment by pren1** [comment]
这个个例已解决，但是房间有两千多个，全爬一遍那真是要了命啦
